### ISSUE TITLE
What are the updates?

### ISSUE THREAD

**Issue by pantera09cat** [austinpilz/FridayThe13th#25]
I have seen "New update!" on your server description. I have played with a friend and we have seen:

- Jason has double jump.
- Now there is Tommy's call in Crystal Lake

Are there more updates? Also we have seen this bug on windows. Check this video: https://www.youtube.com/watch?v=XH-QimgjAAY&feature=youtu.be

Thanks and see you!

**Comment by austinpilz** [comment]
HI!

Thanks so much for reporting the window jumping bug. The first time when it failed because you'd get stuck somewhere is correct. The math is really difficult to have it teleport, so that failure is a failsafe to ensure you don't get stuck and suffocate in a block. Sometimes it has to do with whether you're looking up or down, I'm not able to fully describe it.

As for the new updates, I just updated it to 1.8.3 :)

**Comment by pantera09cat** [comment]
All right, well done! I always played 1.12.2 xD
I think that it could be easier to break all objects in front a window. What dou you think?

Thanks for answer
