### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by Nightmare2013** [austinpilz/FridayThe13th#3]
It is impossible to translate. Did everything as written ,but in the folder "languages" single file, and there "console.message.bootupTime: Startup complete - took {0} ms"
I misunderstood Wikipedia what to do.
Can you help please ?
(Sorry for the error. I'm Russian.)

**Comment by austinpilz** [comment]
Please refer to the [Language API Page](https://dev.bukkit.org/projects/languageapi) for the setup and translation instructions. 

Basically, every time that a message is sent in-game, it adds it to the language file. You'll need to play the game a few times to get the language file to populate with all of the strings so that you can translate them all.

**Comment by Nightmare2013** [comment]
Is it possible to change the name of the game in the scoreboard and [F13] in the chat ? Name not found.
Screenshot http://servokio.tk/s2.png

**Comment by austinpilz** [comment]
It's not possible to change the name of the [F13] chat prefix, but I will add to the next update (coming later tonight) the ability to change the game's name on the scoreboard.
